### ISSUE TITLE
[refactor]: SearchResultView Event Collection UI 변경

### ISSUE THREAD

**Issue by rriver2** [DeveloperAcademy-POSTECH/MC3-Team17-Hou#60]
### Feature 설명

기존의 UI
<img width="199" alt="스크린샷 2022-07-26 오후 10 25 09" src="https://user-images.githubusercontent.com/82457928/181016903-c479b887-87f1-4219-8c51-fb4b6974f51f.png">

변경된 UI
<img width="199" alt="스크린샷 2022-07-26 오후 10 25 12" src="https://user-images.githubusercontent.com/82457928/181016936-7213462d-f4a6-4c87-bc50-260fbdc886d2.png">

@eunbkang 의 도움을 받기로 했습니다

### Related View(Optional)

SearchResult

### 우선순위

★★★★

### 예상 작업 기간

~07/27(수)

**Comment by eunbkang** [comment]
참고한 블로그 링크입니다~ 화이팅!!
[https://baechukim.tistory.com/9](https://baechukim.tistory.com/9)
